
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzddmdwgzcnikqurtnsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6ZGRtZHdnemNuaWtxdXJ0bnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzM1NTQsImV4cCI6MjA2MTk0OTU1NH0.C5cRRKnKyD_RJWxcorE6jieMcTZq9a6cFd0VSGl7jxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type for wishlist table that is not yet in the generated types
export type WishlistItem = {
  id: string;
  user_id: string;
  perfume_id: string;
  created_at: string;
};
